language: ruby

sudo: false

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0

gemfile:
  - test/gemfiles/prawn-2.1
  - test/gemfiles/prawn-2.2

before_install:
  - travis_retry gem update --system

script: bundle exec rake test
